# Generated by Django 3.1.7 on 2021-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile-pic/'),
        ),
    ]
